---
title: "Transportation"
author: "Madhusudhan Masineni"
date: "2022-10-19"
output:
  pdf_document: default
  html_document: default
---



```{r}
library(lpSolve)
```
```{r}
# Solve the transportation Problem in R and formulate it. 
# use Dataframe 
transport = matrix(c(22,14,30,600,100,
               16,20,24,625,120,
               80,60,70,"-","-"),ncol=5,byrow=TRUE)
colnames(transport)=c("Warehouse-1","Warehouse-2","Warehouse-3","Production cost","Production capacity")
rownames(transport)=c("Plant-A","Plant-B","Demand")
transport

```


```{r }
# THE Transportation model and the Objective Function solved below 
# Minimization:: The combined cost of a production and shipping
# Min TM = 22x11 + 14x12 + 30x13+ 16x21 + 20x22+ 24x23
#  which is Subjected to supply constraints:
# x11 + x12 + x13 <= 100 (Plant-A)
# x21 + x22 + x23 >= 120 (Plant-B)
# Demand Constraints 
# x11 + x21 >= 80 (Warehouse-1)
# x12 + x22 >= 60 (Warehouse-2)
# x13 + x23 >= 70 (Warehouse-3)
# Seems to be the transportation problem is unbalanced because demand < supply by 10.
# Use dummy variable method column 4 with the transportation cost = 0 and demand = 10.

# Transportation problem in R

tp <- matrix(c(622,614,630,0,
                  641,645,649,0), ncol = 4, byrow = TRUE)
# Column names, row names 
colnames(tp) <- c("Warehouse-1", "Warehouse-2", "Warehouse-3", "Dummy")
row.names(tp) <- c("Plant-A", "PLant-B")
tp <- as.table(tp)
tp

# Production Capacity set row :
# supply end
rowsign <- rep("<=", 2)
rowrhs <- c(100,120)

# demand end
colsign <- rep(">=", 4)
colrhs <- c(80,60,70,10)

# LP Transport to find min.cost
lpt <- lp.transport(tp, "min", rowsign, rowrhs, colsign, colrhs)

# solution
lpt$solution

# objective function
lpt$objval

# Objective function is 132790
# Plant A they should ship 40 to Warehouse 1 and 60 units to Warehouse 2,from Plant B they should ship 40 units to Warehouse 1 and 70 units to Warehouse 3,giving an overall total cost of $132,790.

# The dual
lpt$duals
# Dual is the shadow prices of primal.


# 3. Make an economic interpretation of the dual 
# Warehouse-1 <= 622 + Plant-A
# Warehouse-2 <= 614 + Plant-A
# Warehouse-3 <= 630 + Plant-A
# Warehouse-1 <= 641 + PlantB
# Warehouse-2 <= 645 + PlantB
# Warehouse-3 <= 649 + PlantB

#We conclude that Warehouse-1 - Plant-A >= 622$$ that can be exponented as arehouse-1 <= 622 + Plant-A
# Warehouse-1 is considered as the price payments being  received  at  the  origin  which  is  nothing  else, but  the  revenue, whereas Plant-A + 622  is  the  money  paid  at  the  origin  at  Plant-A 
# Therefore  the  equation  turns,  out to be  MarketRevenue >= MarginalCost_1

# For  a  profit  maximization,  The  Marginal  Revenue (MR) should be equal to Marginal Costs MR_1 = MC_1

#Based  on above interpretation, we can conclude that, Profit maximization takes place  if MC is equal to MR.

# If MR < MC, We must lower plant costs in order to reach the Marginal Revenue (MR)
  
#If MR > MC, We must boost manufacturing supply if we are to reach the Marginal Revenue (MR)
 
 4.# Conclusion from the primal
# 60x12 which is 60 Units from Plant A to Warehouse 2.
# 40x13 which is 40 Units from Plant A to Warehouse 3.
# 80x21 which is 60 Units from Plant B to Warehouse 1.
# 30x23 which is 60 Units from Plant B to Warehouse 3.
# from the dual
# So, MR=MC. Five of the six MR<=MC. The only equation that does not satisfy this requirement is Plant B to
# Warehouse 2. 
#The primal that we will not be shipping any AED device there

```
